#!/bin/ksh
#######################################################################
##   File                : teamwork
##   Date                : 10th July 2018
##   Author              : Sunil
##   Remarks             : my Notes on TeamWork
##                              1) initial creation 
##                              2) Free space in tablespaces
##                              3) Disk space statistics
##  ###################################################################

mention the story of ICRISAT and ask at what stage is the team formed. 
- there are no right and wrong answers but it tells a lot about who you are 
and that is not going to change for a long time to come..

you are trying to accept people as they are and then trying to do good stuff
